# Generated by Django 3.2 on 2021-04-16 10:35

import dashboard.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', dashboard.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
